// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQMsCyMfR4AJnlWNT-yvTPzQ9Wu-Pw6D0',
    appId: '1:689376050338:web:c8a064c14259d39d4debfb',
    messagingSenderId: '689376050338',
    projectId: 'videocall-488b0',
    authDomain: 'videocall-488b0.firebaseapp.com',
    storageBucket: 'videocall-488b0.firebasestorage.app',
    measurementId: 'G-ZE8W63NS8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOQbHiWAgbKwa4Shx3U9YwpnxziXLOfpc',
    appId: '1:689376050338:android:d46b1c82e4d7b8994debfb',
    messagingSenderId: '689376050338',
    projectId: 'videocall-488b0',
    storageBucket: 'videocall-488b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvjsojfgKEwP8RQQ1wVrHUWGgmniv0Fno',
    appId: '1:689376050338:ios:ab59b5b40b9bfaa54debfb',
    messagingSenderId: '689376050338',
    projectId: 'videocall-488b0',
    storageBucket: 'videocall-488b0.firebasestorage.app',
    iosBundleId: 'com.example.videoCallAssigment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvjsojfgKEwP8RQQ1wVrHUWGgmniv0Fno',
    appId: '1:689376050338:ios:ab59b5b40b9bfaa54debfb',
    messagingSenderId: '689376050338',
    projectId: 'videocall-488b0',
    storageBucket: 'videocall-488b0.firebasestorage.app',
    iosBundleId: 'com.example.videoCallAssigment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQMsCyMfR4AJnlWNT-yvTPzQ9Wu-Pw6D0',
    appId: '1:689376050338:web:279900d0dfbbe6f14debfb',
    messagingSenderId: '689376050338',
    projectId: 'videocall-488b0',
    authDomain: 'videocall-488b0.firebaseapp.com',
    storageBucket: 'videocall-488b0.firebasestorage.app',
    measurementId: 'G-PT55E8TF13',
  );
}
